"""Build a downloadable Product Requirements Document from CTO artifacts."""

from __future__ import annotations

from typing import Any


def _bullets(items: list[Any], empty: str = "Not specified.") -> str:
    if not items:
        return empty
    lines: list[str] = []
    for item in items:
        if isinstance(item, dict):
            name = item.get("name") or item.get("title") or item.get("phase") or "Item"
            detail = item.get("description") or item.get("summary") or item.get("rationale") or ""
            priority = item.get("priority")
            suffix = f" ({priority})" if priority else ""
            lines.append(f"- **{name}**{suffix}: {detail}".rstrip(": "))
        else:
            lines.append(f"- {item}")
    return "\n".join(lines)


def build_prd(idea: str, artifacts: dict[str, Any]) -> str:
    """Create a complete Markdown PRD from persisted project artifacts."""
    arts = artifacts or {}
    plan = arts.get("plan") or {}
    research = arts.get("market_research") or {}
    features = arts.get("features") or []
    architecture = arts.get("architecture") or {}
    database = arts.get("database_schema") or {}
    endpoints = arts.get("api_endpoints") or []
    roadmap = arts.get("roadmap") or []
    critic = arts.get("critic_review") or {}
    cost = arts.get("cost_estimate") or {}
    board = arts.get("review_board") or {}
    if not board and (critic or cost or architecture):
        from app.services.review_board import build_review_board

        board = build_review_board(idea, arts)

    title = plan.get("title") or "Product Requirements Document"
    endpoint_lines = [
        f"- `{ep.get('method', 'GET')} {ep.get('path', '/')}` — {ep.get('summary', '')}"
        for ep in endpoints
    ]
    entity_lines = [
        f"- **{entity.get('name', 'Entity')}**: "
        + ", ".join(field.get("name", "field") for field in entity.get("fields", []))
        for entity in database.get("entities", [])
    ]
    roadmap_lines = [
        f"- **{item.get('phase', 'Phase')} — {item.get('title', '')}** "
        f"({item.get('duration_weeks', '?')} weeks): "
        + ", ".join(item.get("deliverables", []))
        for item in roadmap
    ]

    return f"""# {title}

## Document status

- **Version:** 1.0
- **Generated by:** ForgeCTO
- **Status:** Draft for founder and engineering review

## 1. Product overview

### Startup idea

{idea}

### Problem statement

{plan.get("problem_statement") or "Not specified."}

### Product domain

{plan.get("domain") or "Not specified."}

## 2. Target users

{_bullets(plan.get("target_users") or [])}

## 3. Market context

{research.get("market_summary") or "Market research not available."}

### Opportunities

{_bullets(research.get("opportunities") or [])}

### Market and product risks

{_bullets(research.get("risks") or [])}

## 4. Product goals and success metrics

{_bullets(plan.get("success_metrics") or [])}

## 5. MVP scope

{_bullets(plan.get("mvp_scope") or [])}

## 6. Future scope

{_bullets(plan.get("later_scope") or [])}

## 7. Functional requirements

{_bullets(features)}

## 8. User stories

{_user_stories(plan.get("target_users") or [], features)}

## 9. Non-functional requirements

{_bullets(architecture.get("non_functional_requirements") or [
    "Secure authentication and authorization",
    "Reliable backups and recovery",
    "Observable APIs with structured logs",
    "Responsive user experience",
])}

## 10. Technical architecture

{architecture.get("rationale") or "See the Architecture tab for the recommended design."}

### Recommended stack

{_stack_lines(architecture.get("recommended_stack") or {})}

## 11. Data model

{chr(10).join(entity_lines) if entity_lines else "No database entities specified."}

## 12. API requirements

{chr(10).join(endpoint_lines) if endpoint_lines else "No API endpoints specified."}

## 13. Delivery roadmap

{chr(10).join(roadmap_lines) if roadmap_lines else "No roadmap specified."}

## 14. Cost and timeline

- **Build timeline:** {cost.get("build_weeks_low", "?")}–{cost.get("build_weeks_high", "?")} weeks
- **Engineering estimate:** ${cost.get("engineering_cost_low_usd", "?")}–${cost.get("engineering_cost_high_usd", "?")}
- **Monthly infrastructure:** ${cost.get("monthly_infra_low_usd", "?")}–${cost.get("monthly_infra_high_usd", "?")}

## 15. Acceptance criteria

- Every P0 feature has a documented user flow, API, and data model.
- Critical write operations enforce authentication and role checks.
- Core workflows have validation, useful errors, and test coverage.
- Production deployment includes monitoring, backups, and secret management.
- Founder reviews and accepts the MVP scope before implementation begins.

## 16. AI CTO Review Board

- **Architecture score:** {board.get("architecture_score", "—")} / 100
- **Scalability:** {board.get("scalability", "—")} / 100
- **Security:** {board.get("security", "—")} / 100
- **Cost efficiency:** {board.get("cost_efficiency", "—")} / 100
- **Development time:** {board.get("development_time_months", "—")} months
- **Hiring estimate:** {board.get("hiring_estimate_engineers", "—")} engineers
- **AWS monthly cost:** ${board.get("aws_monthly_cost_usd", "—")}
- **Risk score:** {board.get("risk_score", "—")}
- **Production readiness:** {board.get("production_readiness", "—")}%
- **Investor readiness:** {board.get("investor_readiness", "—")}%

{board.get("executive_summary") or "No review board summary available."}

### Investor pitch bullets

{_bullets(board.get("investor_pitch_bullets") or [])}

## 17. Critic review

- **Overall score:** {critic.get("overall_score", "Not scored")} / 100
- **Buildability:** {critic.get("buildability", "Not scored")} / 100
- **Market fit:** {critic.get("market_fit", "Not scored")} / 100
- **Technical risk:** {critic.get("technical_risk", "Not scored")} / 100

{critic.get("summary") or "No critic summary available."}

### Must fix before launch

{_bullets(critic.get("must_fix_before_launch") or [])}

## 18. Assumptions

{_bullets(plan.get("assumptions") or [])}
"""


def _user_stories(users: list[Any], features: list[Any]) -> str:
    personas = [str(user) for user in users] or ["primary user"]
    if not features:
        return "- As a primary user, I want to complete the core workflow so that I receive product value."
    stories: list[str] = []
    for index, feature in enumerate(features[:12]):
        name = feature.get("name", "use the feature") if isinstance(feature, dict) else str(feature)
        detail = feature.get("description", "") if isinstance(feature, dict) else ""
        persona = personas[index % len(personas)]
        stories.append(f"- As a **{persona}**, I want to **{name.lower()}** so that {detail.lower() or 'I achieve my goal'}.")
    return "\n".join(stories)


def _stack_lines(stack: dict[str, Any]) -> str:
    if not stack:
        return "Not specified."
    return "\n".join(f"- **{key.replace('_', ' ').title()}:** {value}" for key, value in stack.items())
